import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Inter({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        elements: {
          // Sign-in modal container - matches --card in dark mode
          card: {
            boxShadow:
              "0 20px 25px -5px rgb(0 0 0 / 0.5), 0 8px 10px -6px rgb(0 0 0 / 0.5)",
            borderRadius: "1rem",
            border: "1px solid rgba(255, 255, 255, 0.1)",
            backgroundColor: "rgb(24, 24, 24)",
          },
          // Header styling - matches --foreground in dark mode
          headerTitle: {
            color: "rgb(251, 251, 251)",
            fontWeight: "600",
            fontSize: "1.5rem",
          },
          headerSubtitle: {
            color: "rgb(180, 180, 180)",
            fontSize: "0.875rem",
          },
          // Form fields - matches --input and --foreground in dark mode
          formFieldInput: {
            borderRadius: "0.5rem",
            borderColor: "rgba(255, 255, 255, 0.15)",
            backgroundColor: "rgb(31, 31, 31)",
            color: "rgb(251, 251, 251)",
            fontSize: "0.875rem",
            padding: "0.75rem 1rem",
          },
          formFieldLabel: {
            color: "rgb(251, 251, 251)",
            fontWeight: "500",
            fontSize: "0.875rem",
          },
          // Buttons - matches your app's gradient style
          formButtonPrimary: {
            background:
              "linear-gradient(to right, rgb(249 115 22), rgb(245 158 11))",
            color: "white",
            fontWeight: "600",
            fontSize: "0.875rem",
            padding: "0.75rem 1.5rem",
            borderRadius: "0.5rem",
            boxShadow: "0 4px 6px -1px rgb(0 0 0 / 0.3)",
          },
          formButtonPrimary__loading: {
            background:
              "linear-gradient(to right, rgb(249 115 22), rgb(245 158 11))",
          },
          // Social buttons - matches --muted and --foreground in dark mode
          socialButtonsBlockButton: {
            borderColor: "rgba(255, 255, 255, 0.1)",
            backgroundColor: "rgb(31, 31, 31)",
            color: "rgb(251, 251, 251)",
            borderRadius: "0.5rem",
            padding: "0.75rem 1rem",
            fontSize: "0.875rem",
            fontWeight: "500",
          },
          socialButtonsBlockButton__google: {
            color: "rgb(251, 251, 251)",
          },
          // Footer links - matches your brand color
          footerActionLink: {
            color: "rgb(249 115 22)",
            fontWeight: "500",
            fontSize: "0.875rem",
          },
          footerActionText: {
            color: "rgb(180, 180, 180)",
            fontSize: "0.875rem",
          },
          // Footer branding - "Secured by Clerk"
          footerBranding: {
            color: "rgb(180, 180, 180)",
            fontSize: "0.75rem",
          },
          footerBrandingBox: {
            backgroundColor: "transparent",
          },
          // Entire footer section
          footer: {
            backgroundColor: "rgb(24, 24, 24)",
            borderTop: "1px solid rgba(255, 255, 255, 0.1)",
          },
          // Divider - matches --border in dark mode
          dividerLine: {
            borderColor: "rgba(255, 255, 255, 0.1)",
          },
          dividerText: {
            color: "rgb(180, 180, 180)",
            fontSize: "0.875rem",
          },
          // Error messages
          formFieldErrorText: {
            color: "rgb(248 113 113)",
            fontSize: "0.75rem",
          },
          // Success messages
          formFieldSuccessText: {
            color: "rgb(74 222 128)",
            fontSize: "0.75rem",
          },
        },
      }}
    >
      <ThemeProvider defaultTheme="system" storageKey="yum-yum-theme">
        <html lang="en" suppressHydrationWarning>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            {children}
            <Toaster position="top-right" richColors />
          </body>
        </html>
      </ThemeProvider>
    </ClerkProvider>
  );
}
