-- AlterTable
ALTER TABLE "User" ADD COLUMN "streak" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "points" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "lastLoginDate" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN "streakStartDate" TIMESTAMP(3);
